[[redirects]]
  from = "/api/fetch-dados"
  to = "https://firebasestorage.googleapis.com/v0/b/arrecadacao-arapiraca.appspot.com/o/dados.csv?alt=media"
  status = 200
  force = true
  headers = { X-Forwarded-For = "https://arrecadacao-arapiraca.netlify.app" }

